### ISSUE TITLE
Code Issue: Import 7/10: Issue with as.numeric

### ISSUE THREAD

**Issue by GretaKu** [UniLuFS2020-ReplicationSeminar/ReplicationPaperGreta#3]
Hi Andrea
I have an issue. I am preparing the 26 panel data sets from countries in america for binding and one variable "qi1" is everywhere numeric expect for 2 datasets (US and Canada). There it is a character variable.
The author has "as.numeric"function in the code, which does not work. It only gives NA (since there are only strings...)
I downloaded the data from LAPOP page and it is exactly the same data file the author used, I doublechecked.

See: 2_Scripts/01_Data collection.R - Import 7/10

Can you advise how I shall proceed here? Maybe contact the author?

**Comment by DeAngelisA** [comment]
@GretaKu : [this one](https://github.com/UniLuFS2020-ReplicationSeminar/ReplicationPaperGreta/blob/3370d7dfdf400911e8525c61ffcc41e12d068a5f/2_Scripts/01_Data%20collection.R#L70)? `fecha` in Spanish means "date", is that a date variable? Shouldn't this be the joining key? Anyways, I would maybe try `as.numeric(as.character())`.

**Comment by GretaKu** [comment]
@DeAngelisA Thank you for your quick reply! No, the date variable fecha worked to make numeric (the other datasets have it in numeric form). The problematic lines are the following

```
data_Canada$gi1 <- as.numeric(data_Canada$gi1)
data_US$gi1 <- as.numeric(data_US$gi1)
data_Brazil$ti <- as.numeric(data_Brazil$ti)
data_Brazil$intid <- as.numeric(data_Brazil$intid)
```

If I try `data_Canada$gi1 <- as.numeric(as.character(data_Canada$gi1))` it gives me still NAs...

The question for this is "What is the name of the current president of the United States? [Don’t read: Barack Obama, accept “Obama”]
(1) Correct (2) Incorrect (88) DK (98) DA "

But the variable is character like "Obama","B. Obama", "Barak Obama" etc.
I could switch them manually with `ifelse` to numeric but since I have spotted a lot of typos it would take a long time and it could generate errors. But I see no other option..

**Comment by DeAngelisA** [comment]
Fixed
